
ALTER TABLE NATION
DROP CONSTRAINT nation_n_regionkey_fkey;

ALTER TABLE LINEITEM
DROP CONSTRAINT lineitem_l_orderkey_fkey;

ALTER TABLE LINEITEM
DROP CONSTRAINT lineitem_l_partkey_l_suppkey_fkey;
	
ALTER TABLE CUSTOMER
DROP CONSTRAINT customer_c_nationkey_fkey;
		
ALTER TABLE ORDERS
DROP CONSTRAINT orders_o_custkey_fkey;

	
ALTER TABLE PARTSUPP
DROP CONSTRAINT partsupp_ps_partkey_fkey;

ALTER TABLE PARTSUPP
DROP CONSTRAINT partsupp_ps_suppkey_fkey;


ALTER TABLE SUPPLIER
DROP CONSTRAINT supplier_s_nationkey_fkey;





ALTER TABLE NATION
DROP CONSTRAINT nation_pkey;

ALTER TABLE LINEITEM
DROP CONSTRAINT lineitem_pkey;


ALTER TABLE CUSTOMER
DROP CONSTRAINT customer_pkey;
		
ALTER TABLE ORDERS
DROP CONSTRAINT orders_pkey;

	
ALTER TABLE PART
DROP CONSTRAINT part_pkey;

ALTER TABLE PARTSUPP
DROP CONSTRAINT partsupp_pkey;


ALTER TABLE SUPPLIER
DROP CONSTRAINT supplier_pkey;

		
ALTER TABLE REGION
DROP CONSTRAINT region_pkey;
